import type { Metadata } from "next";
import "./globals.css";
import { UserProvider } from "@/context/UserContext"; // Importa tu UserProvider
import ClientLayout from "@/components/ClientLayout"; // Nuevo componente cliente

export const metadata: Metadata = {
  title: "Romulo Gallegos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          {/* Mover la lógica de cliente aquí */}
          <ClientLayout>{children}</ClientLayout>
        </UserProvider>
      </body>
    </html>
  );
}
